# -*- coding: utf-8 -*-
"""grafosTrabalho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wl1YWTRfD8HXkiDtAOrk7EGZA6kDvl5t
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile grafo.txt
# 2
# 70
# 0 "The Witcher 3"
# 1 "Skyrim"
# 2 "Elden Ring"
# 3 "Baldur's Gate 3"
# 4 "Cyberpunk 2077"
# 5 "Fallout 4"
# 6 "Starfield"
# 7 "Dragon Age: Inquisition"
# 8 "Mass Effect Legendary"
# 9 "Final Fantasy VII Remake"
# 10 "GTA V"
# 11 "Red Dead Redemption 2"
# 12 "God of War Ragnarok"
# 13 "Horizon Forbidden West"
# 14 "Spider-Man 2"
# 15 "Ghost of Tsushima"
# 16 "The Last of Us Part II"
# 17 "Uncharted 4"
# 18 "Assassin's Creed Valhalla"
# 19 "Hogwarts Legacy"
# 20 "Call of Duty: MW3"
# 21 "Battlefield 2042"
# 22 "Counter-Strike 2"
# 23 "Valorant"
# 24 "Overwatch 2"
# 25 "Apex Legends"
# 26 "Doom Eternal"
# 27 "Halo Infinite"
# 28 "Destiny 2"
# 29 "Rainbow Six Siege"
# 30 "Forza Horizon 5"
# 31 "Gran Turismo 7"
# 32 "Need for Speed Unbound"
# 33 "F1 24"
# 34 "Assetto Corsa Competizione"
# 35 "Dirt 5"
# 36 "Burnout Paradise"
# 37 "Project Cars 3"
# 38 "Grid Legends"
# 39 "The Crew Motorfest"
# 40 "EA FC 24"
# 41 "NBA 2K24"
# 42 "Madden NFL 24"
# 43 "Rocket League"
# 44 "Stardew Valley"
# 45 "The Sims 4"
# 46 "Animal Crossing: New Horizons"
# 47 "Cities: Skylines II"
# 48 "Minecraft"
# 49 "Terraria"
# 50 "League of Legends"
# 51 "Dota 2"
# 52 "Civilization VI"
# 53 "Age of Empires IV"
# 54 "StarCraft II"
# 55 "Hearthstone"
# 56 "XCOM 2"
# 57 "Stellaris"
# 58 "Crusader Kings III"
# 59 "Baldur's Gate 2"
# 60 "Hades"
# 61 "Hollow Knight"
# 62 "Celeste"
# 63 "Cuphead"
# 64 "Dead Cells"
# 65 "Vampire Survivors"
# 66 "Subnautica"
# 67 "Sons of the Forest"
# 68 "Rust"
# 69 "Ark: Survival Ascended"
# 185
# 0 1 5
# 0 2 4
# 0 3 5
# 0 7 4
# 0 8 3
# 1 2 4
# 1 5 5
# 1 6 4
# 1 19 4
# 2 3 4
# 2 12 3
# 2 15 3
# 2 60 2
# 3 7 5
# 3 59 5
# 3 50 2
# 4 5 5
# 4 6 5
# 4 8 4
# 5 6 5
# 5 69 3
# 7 8 5
# 7 9 3
# 9 12 3
# 9 13 3
# 10 11 5
# 10 14 3
# 10 18 3
# 11 15 4
# 11 16 3
# 12 13 4
# 12 14 4
# 12 15 5
# 13 14 4
# 13 15 4
# 13 19 3
# 14 15 4
# 14 17 5
# 15 18 4
# 16 17 5
# 16 67 2
# 18 19 4
# 20 21 5
# 20 22 4
# 20 25 4
# 20 28 3
# 21 22 4
# 21 27 3
# 21 29 4
# 22 23 5
# 22 29 5
# 23 24 5
# 23 25 4
# 24 25 5
# 24 28 4
# 26 27 4
# 26 28 3
# 27 28 5
# 30 31 5
# 30 32 5
# 30 33 3
# 30 39 5
# 31 33 4
# 31 34 5
# 32 36 5
# 32 39 4
# 33 34 4
# 33 38 4
# 34 37 5
# 35 37 4
# 35 38 4
# 36 39 4
# 37 38 5
# 40 41 5
# 40 42 5
# 41 42 5
# 44 45 4
# 44 46 5
# 44 49 4
# 45 46 4
# 45 47 3
# 48 49 5
# 48 66 3
# 48 69 4
# 49 61 3
# 49 64 3
# 50 51 5
# 50 55 3
# 51 54 4
# 52 53 4
# 52 57 5
# 52 58 5
# 53 54 5
# 56 57 4
# 57 58 5
# 60 61 4
# 60 64 5
# 60 65 4
# 61 62 4
# 61 64 4
# 62 63 5
# 64 65 4
# 66 67 5
# 66 69 4
# 67 68 5
# 68 69 5
# 0 4 3
# 2 13 3
# 3 56 3
# 10 32 2
# 11 67 2
# 20 23 3
# 30 43 2
# 40 43 3
# 44 48 4
# 52 56 3
# 1 7 3
# 2 9 2
# 4 28 2
# 10 17 4
# 11 18 3
# 12 16 3
# 13 18 4
# 14 16 3
# 15 17 3
# 19 28 2
# 21 25 3
# 22 24 3
# 26 29 2
# 27 29 2
# 31 37 3
# 32 35 3
# 34 38 3
# 35 36 2
# 36 38 3
# 41 43 2
# 42 43 2
# 45 48 3
# 46 48 3
# 47 52 4
# 50 54 3
# 51 55 2
# 53 56 3
# 54 55 2
# 55 56 2
# 57 58 4
# 59 60 2
# 62 64 3
# 63 65 2
# 66 68 4
# 67 69 4
# 0 11 3
# 1 19 3
# 4 20 2
# 5 68 3
# 8 28 4
# 9 15 2
# 10 30 2
# 12 60 3
# 13 14 4
# 14 18 3
# 16 66 2
# 21 28 3
# 22 23 4
# 25 43 3
# 26 27 4
# 30 35 3
# 31 32 3
# 33 34 4
# 34 37 3
# 39 43 2
# 44 47 2
# 46 49 3
# 48 67 4
# 50 52 2
# 51 53 2
# 54 56 3
# 60 62 3
# 61 63 3
# 64 66 2
# 65 67 2

# =======================================================================
# Nomes: Beatriz Aparecida de Mello Barbosa (10354067)
#        Matheus Veiga Bacetic Joaquim (10425638)
#        Gabriel Pereira Faravola (10427189)
# Síntese: Aplicação para modelagem e manipulação de um grafo de
#          recomendação de jogos (Não-Direcionado, Ponderado nas Arestas)
# Histórico:
#   - 13/03 - Implementação do menu inicial
#   - Atualização - Migração de Matriz para Lista de Adjacência para
#     suportar 70+ vértices de forma legível e otimizada.
# =======================================================================

import os

class GrafoRecomendacao:
    def __init__(self):
        self.tipo = 2  # 2 = Não orientado com peso na aresta
        self.V = 0
        self.rotulos = {}
        # Lista de Adjacência: uma lista onde cada índice tem um dicionário {id_vizinho: peso}
        self.adj = []

    # a) Ler dados do arquivo
    # a) Ler dados do arquivo
    def ler_arquivo(self, nome_arquivo="grafo.txt"):
        try:
            with open(nome_arquivo, 'r', encoding='utf-8') as f:
                # Lê todas as linhas ignorando espaços em branco e linhas vazias
                linhas = [l.strip() for l in f.readlines() if l.strip()]

            if len(linhas) < 2:
                print("\n[-] O arquivo está vazio ou incompleto.")
                return

            self.tipo = int(linhas[0])
            self.V = int(linhas[1])
            self.adj = [{} for _ in range(self.V)]
            self.rotulos = {}

            linha_atual = 2

            # 1. Lendo os vértices com segurança
            for _ in range(self.V):
                if linha_atual < len(linhas):
                    partes = linhas[linha_atual].split('"')
                    id_v = int(partes[0].strip())
                    # Se tiver nome entre aspas pega, se não, cria um genérico
                    nome = partes[1].strip() if len(partes) > 1 else f"Desconhecido {id_v}"
                    self.rotulos[id_v] = nome
                    linha_atual += 1
                else:
                    break # Se acabaram as linhas, para de ler

            # Verifica se ainda tem linhas para ler as arestas
            if linha_atual < len(linhas):
                # Pula a linha que diz "quantas arestas tem"
                linha_atual += 1

                # 2. Lendo as arestas ATÉ O ARQUIVO ACABAR
                num_arestas_lidas = 0
                while linha_atual < len(linhas):
                    try:
                        u, v, peso = map(int, linhas[linha_atual].split())
                        # Só adiciona se os IDs dos vértices existirem para não dar KeyError
                        if u < self.V and v < self.V:
                            self.adj[u][v] = peso
                            self.adj[v][u] = peso  # Não direcionado
                            num_arestas_lidas += 1
                    except ValueError:
                        # Se a linha estiver mal formatada (ex: uma letra no lugar de número), ignora
                        pass
                    linha_atual += 1

            # Depois de ler de forma segura, atualiza o 'V' real caso o arquivo estivesse quebrado
            self.V = len(self.rotulos)
            self.adj = self.adj[:self.V] # Garante que a lista de adjacência tenha o tamanho certo

            print(f"\n[+] Sucesso! Grafo carregado com {self.V} jogos e {num_arestas_lidas} conexões.")

        except FileNotFoundError:
             print(f"\n[-] Erro: Arquivo '{nome_arquivo}' não encontrado.")
        except Exception as e:
            print(f"\n[-] Erro inesperado ao ler arquivo: {e}")

    # b) Gravar dados no arquivo
    def gravar_arquivo(self, nome_arquivo="grafo.txt"):
        try:
            arestas = []
            for u in range(self.V):
                for v, peso in self.adj[u].items():
                    # u <= v evita duplicar arestas no TXT (já que é não direcionado)
                    if u <= v:
                        arestas.append((u, v, peso))

            with open(nome_arquivo, 'w', encoding='utf-8') as f:
                f.write(f"{self.tipo}\n")
                f.write(f"{self.V}\n")
                for i in range(self.V):
                    f.write(f'{i} "{self.rotulos.get(i, "Desconhecido")}"\n')
                f.write(f"{len(arestas)}\n")
                for u, v, peso in arestas:
                    f.write(f"{u} {v} {peso}\n")
            print(f"\n[+] Dados salvos com sucesso em '{nome_arquivo}'!")
        except Exception as e:
            print(f"\n[-] Erro ao gravar arquivo: {e}")

    # c) Inserir vértice
    def inserir_vertice(self, nome):
        novo_id = self.V
        self.adj.append({})  # Adiciona uma nova lista de adjacência vazia
        self.rotulos[novo_id] = nome
        self.V += 1
        print(f"\n[+] Jogo '{nome}' inserido com ID {novo_id}.")

    # d) Inserir aresta
    def inserir_aresta(self, u, v, peso):
        if 0 <= u < self.V and 0 <= v < self.V:
            self.adj[u][v] = peso
            self.adj[v][u] = peso
            print(f"\n[+] Conexão criada entre '{self.rotulos[u]}' e '{self.rotulos[v]}' (Similaridade: {peso}).")
        else:
            print("\n[-] IDs de vértices inválidos.")

    # e) Remover vértice (Reordena os IDs nas Listas de Adjacência)
    def remover_vertice(self, id_v):
        if 0 <= id_v < self.V:
            nome = self.rotulos.pop(id_v)

            # 1. Remove a lista de adjacência do vértice deletado
            self.adj.pop(id_v)
            self.V -= 1

            # 2. Reordena os rótulos para tapar o "buraco"
            for i in range(id_v, self.V):
                self.rotulos[i] = self.rotulos.pop(i + 1)

            # 3. Varre todas as listas de adjacência restantes para atualizar os IDs
            for u in range(self.V):
                nova_adj_u = {}
                for v, peso in self.adj[u].items():
                    if v == id_v:
                        continue  # Ignora a aresta que apontava para o vértice removido
                    elif v > id_v:
                        nova_adj_u[v - 1] = peso  # Rebaixa o ID em 1
                    else:
                        nova_adj_u[v] = peso
                self.adj[u] = nova_adj_u

            print(f"\n[+] Jogo '{nome}' (antigo ID {id_v}) removido!")
            print("[+] Lista de adjacência e IDs subsequentes reordenados automaticamente.")
        else:
            print("\n[-] ID inválido.")

    # f) Remover aresta
    def remover_aresta(self, u, v):
        if 0 <= u < self.V and 0 <= v < self.V:
            if v in self.adj[u]:
                del self.adj[u][v]
                del self.adj[v][u]
                print(f"\n[+] Conexão entre '{self.rotulos[u]}' e '{self.rotulos[v]}' foi desfeita.")
            else:
                print("\n[-] Não existe conexão entre estes jogos.")
        else:
            print("\n[-] IDs inválidos.")

    # g) Mostrar conteúdo do arquivo (Formato Visualmente Atraente e Seguro)
    def mostrar_arquivo(self, nome_arquivo="grafo.txt"):
        print(f"\n{'='*50}")
        print(f"📄 CONTEÚDO DO ARQUIVO: {nome_arquivo}")
        print(f"{'='*50}")
        try:
            with open(nome_arquivo, 'r', encoding='utf-8') as f:
                # Lê o arquivo ignorando linhas totalmente em branco
                linhas = [l.strip() for l in f.readlines() if l.strip()]

            if len(linhas) < 2:
                print("[-] O arquivo está vazio ou incompleto.")
                return

            tipo = linhas[0]
            qtd_v = int(linhas[1])

            print(f"📌 TIPO DO GRAFO: {tipo} (Não-Direcionado Ponderado)")
            print(f"🎮 TOTAL DE VÉRTICES: {qtd_v}")
            print("-" * 50)

            linha_atual = 2
            # Lê os vértices de forma segura, evitando erro de limite
            for _ in range(qtd_v):
                if linha_atual < len(linhas):
                    print(f"   {linhas[linha_atual]}")
                    linha_atual += 1

            if linha_atual < len(linhas):
                qtd_a = linhas[linha_atual]
                print("-" * 50)
                print(f"🔗 TOTAL DE ARESTAS: {qtd_a}")
                print("-" * 50)
                linha_atual += 1

                # Varre o resto do arquivo de forma segura (sem depender do número qtd_a)
                while linha_atual < len(linhas):
                    partes = linhas[linha_atual].split()
                    if len(partes) >= 3:
                        print(f"   ID {partes[0]:<2} <---> ID {partes[1]:<2} | Peso: {partes[2]}")
                    else:
                        print(f"   {linhas[linha_atual]}") # Fallback caso a linha esteja mal formatada
                    linha_atual += 1

        except FileNotFoundError:
            print("[-] Arquivo não encontrado. Grave os dados primeiro.")
        except Exception as e:
            # Se algo der muito errado, ele imprime o formato original bruto para não travar
            print(f"[-] Erro ao formatar: {e}")
            print("\n--- Conteúdo Bruto ---")
            with open(nome_arquivo, 'r', encoding='utf-8') as f:
                print(f.read())
        print(f"{'='*50}")

    # h) Mostrar grafo (LISTA DE ADJACÊNCIA FORMATADA)
    def mostrar_grafo(self):
        if self.V == 0:
            print("\n[-] O grafo está vazio.")
            return

        print("\n--- LISTA DE ADJACÊNCIA (SIMILARIDADE DE JOGOS) ---")
        for i in range(self.V):
            nome = self.rotulos.get(i, f"V{i}")
            conexoes = []

            # Ordena pelos IDs dos vizinhos para ficar bonito na tela
            for vizinho, peso in sorted(self.adj[i].items()):
                nome_viz = self.rotulos.get(vizinho, f"V{vizinho}")
                conexoes.append(f"[{vizinho}: {nome_viz} (peso {peso})]")

            if conexoes:
                print(f"{i:02d} | {nome[:20]:<20} -> " + " -> ".join(conexoes))
            else:
                print(f"{i:02d} | {nome[:20]:<20} -> (Isolado / Nenhuma conexão)")

    # i) Conexidade (Busca de Componentes Conexas)
    def verificar_conexidade(self):
        if self.V == 0:
            print("\n[-] O grafo está vazio.")
            return

        visitados = [False] * self.V
        componentes = []

        for i in range(self.V):
            if not visitados[i]:
                componente_atual = []
                fila = [i]
                visitados[i] = True

                while fila:
                    no = fila.pop(0)
                    componente_atual.append(self.rotulos[no])

                    # Varre apenas os vizinhos reais na lista de adjacência
                    for vizinho in self.adj[no].keys():
                        if not visitados[vizinho]:
                            visitados[vizinho] = True
                            fila.append(vizinho)

                componentes.append(componente_atual)

        print("\n📊 ANÁLISE DE CONEXIDADE DA REDE:")
        if len(componentes) == 1:
            print("[+] Resultado: GRAFO CONEXO.")
            print("    A rede está 100% interligada. É possível alcançar qualquer jogo a partir de outro.")
        else:
            print(f"[-] Resultado: GRAFO DESCONEXO ({len(componentes)} componentes separadas).")
            print("    A rede está fragmentada. Grupos isolados encontrados:")
            for idx, comp in enumerate(componentes, 1):
                print(f"    -> Componente {idx} ({len(comp)} jogos): {', '.join(comp[:5])}{'...' if len(comp)>5 else ''}")

def menu():
    sistema = GrafoRecomendacao()
    while True:
        print("\n=======================================================")
        print(" 🎮 SISTEMA DE RECOMENDAÇÃO DE JOGOS (GRAFOS) 🎮 ")
        print("=======================================================")
        print("a) Ler dados do arquivo grafo.txt")
        print("b) Gravar dados no arquivo grafo.txt")
        print("c) Inserir vértice (Novo Jogo)")
        print("d) Inserir aresta (Conectar Jogos)")
        print("e) Remover vértice (Deletar Jogo)")
        print("f) Remover aresta (Desfazer Conexão)")
        print("g) Mostrar conteúdo do arquivo")
        print("h) Mostrar grafo (Lista de Adjacência)")
        print("i) Apresentar a conexidade do grafo")
        print("j) Encerrar a aplicação")

        opcao = input("\nEscolha sua ação: ").lower()

        if opcao == 'a':
            sistema.ler_arquivo()
        elif opcao == 'b':
            sistema.gravar_arquivo()
        elif opcao == 'c':
            nome = input("Digite o nome do novo jogo: ")
            sistema.inserir_vertice(nome)
        elif opcao == 'd':
            try:
                u = int(input("ID do primeiro jogo: "))
                v = int(input("ID do segundo jogo: "))
                peso = int(input("Quantidade de tags em comum (peso): "))
                sistema.inserir_aresta(u, v, peso)
            except ValueError:
                print("[-] Erro: Digite apenas números inteiros para IDs e Peso.")
        elif opcao == 'e':
            try:
                id_v = int(input("ID do jogo a ser removido: "))
                sistema.remover_vertice(id_v)
            except ValueError:
                print("[-] Erro: Digite um ID numérico válido.")
        elif opcao == 'f':
            try:
                u = int(input("ID do primeiro jogo: "))
                v = int(input("ID do segundo jogo: "))
                sistema.remover_aresta(u, v)
            except ValueError:
                print("[-] Erro: Digite IDs numéricos válidos.")
        elif opcao == 'g':
            sistema.mostrar_arquivo()
        elif opcao == 'h':
            sistema.mostrar_grafo()
        elif opcao == 'i':
            sistema.verificar_conexidade()
        elif opcao == 'j':
            print("\nEncerrando o programa... Obrigado por usar o sistema!\n")
            break
        else:
            print("\n[-] Opção inválida, tente de novo!")

if __name__ == "__main__":
    menu()